# Generated by Django 3.2.12 on 2022-04-27 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.PositiveBigIntegerField()),
                ('patient_name', models.CharField(max_length=50)),
                ('pregancies', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('bp', models.IntegerField()),
                ('skin', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('dpf', models.FloatField()),
                ('age', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
