# Generated by Django 3.2.12 on 2022-04-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historymodel',
            table='HistoryModel',
        ),
    ]
