# Generated by Django 3.2.12 on 2022-04-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_historymodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='datetime',
            field=models.CharField(max_length=50),
        ),
    ]
